<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_pratikkaushik</name>
   <tag></tag>
   <elementGuidId>b413100a-6691-4aa3-8536-7f4a3b750cb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.imdb-header__account-toggle--logged-in.imdb-header__accountmenu-toggle.navbar__user-name.navbar__user-menu-toggle__name.navbar__user-menu-toggle--desktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='imdbHeader']/div[2]/div[6]/div/label[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e95e1749-12f2-4708-9e74-0f6b6b83cb08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imdb-header__account-toggle--logged-in imdb-header__accountmenu-toggle navbar__user-name navbar__user-menu-toggle__name navbar__user-menu-toggle--desktop</value>
      <webElementGuid>e23bfb65-2013-43e2-954f-9a2d6bc4d1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pratikkaushik</value>
      <webElementGuid>a7d62353-aea0-43e0-9ab0-7429426bd7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imdbHeader&quot;)/div[@class=&quot;ipc-page-content-container ipc-page-content-container--center navbar__inner&quot;]/div[@class=&quot;nav__userMenu navbar__user sc-fuISYh hrzrxR&quot;]/div[@class=&quot;sc-jQAyio dUVOWS navbar__flyout--breakpoint-m&quot;]/label[@class=&quot;ipc-btn ipc-btn--single-padding ipc-btn--center-align-content ipc-btn--default-height ipc-btn--core-baseAlt ipc-btn--theme-baseAlt ipc-btn--button-radius ipc-btn--on-textPrimary ipc-text-button navbar__flyout__text-button-after-mobile navbar__user-menu-toggle__button&quot;]/span[@class=&quot;ipc-btn__text&quot;]/span[@class=&quot;imdb-header__account-toggle--logged-in imdb-header__accountmenu-toggle navbar__user-name navbar__user-menu-toggle__name navbar__user-menu-toggle--desktop&quot;]</value>
      <webElementGuid>c774cb9e-b5cb-4f13-b568-73835c4673b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='imdbHeader']/div[2]/div[6]/div/label[2]/span/span</value>
      <webElementGuid>fd9a85ca-460a-4ec4-8911-2dc996d354e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::span[5]</value>
      <webElementGuid>99aac814-dd83-492b-991f-65df9fd1ce06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pratikkaushik'])[2]/preceding::span[1]</value>
      <webElementGuid>de951eca-9b13-4388-a881-c6ccfd778979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your profile'])[1]/preceding::span[3]</value>
      <webElementGuid>cc939ca2-082d-4848-9054-feebb787ca79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pratikkaushik']/parent::*</value>
      <webElementGuid>51912a98-99e0-4364-b23d-524ca708b422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span/span</value>
      <webElementGuid>4ded33a8-e1e7-4034-b1d3-7128ca690c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'pratikkaushik' or . = 'pratikkaushik')]</value>
      <webElementGuid>19f020cd-da23-4056-bdce-200ccea1d394</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
